name: 'Check for forked repo'
description: 'Validates if comment was made on the original repo'

inputs:
  token:
    description: 'GitHub access token'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
