name: 'Create and publish snapshot release'
description: 'Creates and publishes a snapshot release'

inputs:
  token:
    description: 'GitHub access token'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
